### ISSUE TITLE
lack app/src/config.js and app/src/WebService.js file

### ISSUE THREAD

**Issue by pvqu47** [FutureProcessing/DocuHash#1]
Where can I find app/src/config.js file and WebService.js file? Thanks!

**Comment by elkorba** [comment]
Thanks for raising an issue. We've added missing files. In case of any problems please do not hesitate to ask.

**Comment by pvqu47** [comment]
In folder services: web3-utils.js or web3-Utils.js (Capital "U")

**Comment by elkorba** [comment]
require is not case sensitive, but in fact, it could cause some discrepancies on specific OS'es. File updated, web3-utils.js is the correct one.
