### ISSUE TITLE
 This contract object doesn't have address set yet, please set an address first.

### ISSUE THREAD

**Issue by seifallahhomrani1** [FutureProcessing/DocuHash#12]
After running the docker-compose up command, I've faced this issue : 
![image](https://user-images.githubusercontent.com/29190315/143069447-5c1e53f3-94af-4fd3-8c9d-ef3aa3cb8e2d.png)

Any help ?

**Comment by elkorba** [comment]
Did u go through the [article](https://www.future-processing.pl/blog/storing-files-in-a-distributed-file-system-using-blockchain-technology/) that is a step by step guide?

**Comment by seifallahhomrani1** [comment]
Yes sir, I've followed the tutorial and this problem seems to persist, can you please explain what's the main issue ?

**Comment by elkorba** [comment]
Probably some packages and libraries that are used in the project might get an update that caused this issue. 
To avoid installing newer versions automatically with npm install, please edit package.json file and remove all the ^ in the "dependencies" section. This should help, or try to use a docker image instead. 
Hope it helps.
